const membersList = [
  {
    id: 1,
    fullName: "Gene Oh",
    title: "Co-Founder; Co-President",
    imageName: "gene-pic.png",
    bio: "Gene is a junior from Sharon, MA, pursuing a concentration in Computer Science with specializations in AI/ML and Data Science. Also a Head TA for the Brown Computer Science Department and a private writing tutor of three years, Gene has a demonstrated passion for teaching and working with others. Outside of the classroom, he is a member of the Brown Men's Rugby Team and enjoys hiking, swimming, and snowboarding.",
  },
  {
    id: 2,
    fullName: "Jonathan Palfy",
    title: "Co-Founder; Co-President",
    imageName: "johnathan-pic.jpeg",
    bio: "Jonathan is a junior from Marin County, CA, pursuing a concentration in Behavioral Decision Sciences and a certificate in Data Fluency. This interdisciplinary degree focuses on decision making principles in the fields of economics, psychology, political science, and data analysis. Jonathan has also written articles for the Intercollegiate Finance Journal and enjoys playing basketball or hiking in his free time.",
  },
  {
    id: 3,
    fullName: "Nicholas Alioto-Pier",
    title: "Co-Founder; VP of Tech",
    imageName: "nico-pic.jpg",
    bio: "Nicholas is a junior from San Francisco, CA. He is working on completing his Bachelor's and Master's in Computer Science through Brown's 4-year concurrent degree program. Nicholas is particularly interested in artificial intelligence and front-end developement. He previously worked as a Full Stack SWE Intern at MongoDB and a Front-End Intern at Whimstay, Inc. In his free time, Nicholas enjoys surfing, playing sudoku, and reading Supreme Court cases.",
  },
  {
    id: 4,
    fullName: "William McLaren",
    title: "Co-Founder; VP of Operations",
    imageName: "mclaren.jpeg",
    bio: "Will is a junior from Greenwich, CT, pursuing a concentration in Computer Science with tracks in AI/ML and Data. Outside of the classroom, he is a member of the Brown Squash Team and Brown Investment Group. This summer, he will intern as a research analyst at Point72. After Brown, Will intends to pursue a career in finance. In his free time, he enjoys studying the European soccer transfer market.",
  },
  {
    id: 5,
    fullName: "Ben Piekarz",
    title: "Senior Associate",
    imageName: "ben-pic.jpeg",
    bio: "Ben is a junior from Los Altos, CA, studying Computer Science and International and Public Affairs. Before coming to Brown, he's been avidly exploring the startup ecosystem as a fellow at J-Ventures, a Silicon Valley-based Venture Capital fund. On campus, Ben is also involved with Van Wickle Ventures, Brown Investment Group, and TAMID Group. Ben often spends his free time exercising outdoors—running, road biking, snowboarding, or shooting hoops.",
  },
  {
    id: 6,
    fullName: "Sam Shulman",
    title: "Senior Associate",
    imageName: "sam-pic.jpeg",
    bio: "Sam is a sophomore from Toronto, Canada. She’s studying computer science and is specifically interested in AI/ML and the UI/UX design aspect of computer-human interactions. Sam is also fascinated with Behavioral Decisions Sciences and works as a research assistant at the FeldmanHall Social and Affective Neuroscience Lab. She enjoys giving back to the community by teaching CS at local high schools and volunteering with Best Buddies. In her free time, she enjoys the outdoors and playing hockey.",
  },
  {
    id: 7,
    fullName: "Andre Metzger",
    title: "Senior Associate",
    imageName: "andre-pic.png",
    bio: "Andre is a junior from Boulder, CO, pursuing a concentration in Applied Mathematics-Biology and fulfilling the pre-medical track. A member of the Borton Lab at Brown, Andre is applying probabilistic methods and machine learning to develop a spinal neural prosthetic. Prior to BTCG, Andre was a Senior Analyst with the Brown Healthcare Investment Group. Outside of the classroom, Andre is an avid runner and skier and loves any activity that can get him into the mountains.",
  },
  {
    id: 8,
    fullName: "Mebele Onwuaduegbo",
    title: "Senior Associate",
    imageName: "mebele-pic.png",
    bio: "Mebele is a sophomore from Indianapolis, IN, pursuing a concentration in Computer Science and a certificate in Entrepreneurship and Innovation. Outside of the classroom, she is a first-year liaison for the National Society of Black Engineers chapter on campus and has participated in Brown’s Innovation Dojo Program. After graduating, Mebele plans to pursue a career with a combination of technology and business. Mebele enjoys baking, riding her bike, and weight lifting in her free time.",
  },
  {
    id: 9,
    fullName: "Bridget Griswold",
    title: "Senior Associate",
    imageName: "bridget-pic.jpeg",
    bio: "Bridget is a senior from Orange County, California, studying Computer Science and Business. She is the Director of Brown Entrepreneurship’s Innovation Dojo, where she walks 20 students though the development of their own startups each semester. She has experience with robotics and semiconductors, with a previous internship at KLA. This Summer, Bridget will work as a Technical Program Manager Intern at Meta in their New York City office.",
  },
  {
    id: 10,
    fullName: "Filip Aleksic",
    title: "Senior Associate",
    imageName: "filip-pic.jpeg",
    bio: "Filip is a junior from Belgrade, Serbia, pursuing a concentration in Applied Mathematics-Computer Science with focuses in AI/ML and Data Science. He is also a Data Analyst at the Brown Daily Herald and has previous experience with customer segmentation strategy and credit card delinquency detection. Outside of the classroom, Filip is a member of the Men’s Varsity Water Polo Team and enjoys watching sports as well as exploring coffee shops with friends.",
  },
  {
    id: 11,
    fullName: "Paige Pedrero",
    title: "Senior Associate",
    imageName: "paige-pic.jpeg",
    bio: "Paige is a junior from San Francisco, CA, concentrating in International and Public Affairs with a focus in policy and governance and Entrepreneurship. She currently serves as a Teaching Assistant for business classes at Brown. Additionally, Paige is a mentor for Innovation Dojo, a student-run startup accelerator. Paige also has experience working in commercial real estate investment. In her free time, she enjoys running, backpacking, and playing tennis.",
  },
  {
    id: 12,
    fullName: "Paul Muser",
    title: "Senior Associate",
    imageName: "paul-pic.jpeg",
    bio: "Paul is a junior from Belmont, MA, pursuing a dual concentration in Business Economics and Computer Science. He is also an active member of the Brown Investment Group, where he is on the Research Committee. Recently, Paul has also gotten involved in Economics Research at Brown, where he has used Python and Stata to gather insights on the impact of Medieval Catholic Frescoes in Denmark. Outside of the classroom, Paul enjoys playing for the Brown Men's Rugby Team.",
  },
  {
    id: 13,
    fullName: "Jacob Lewis",
    title: "Senior Associate",
    imageName: "jlew-pic.jpeg",
    bio: "Jacob is a junior from Rye Brook, NY, concentrating in Applied Mathematics-Economics on the Advanced Economics track. From a young age, he has taken a passion for sports of all varieties and their analytical nature. He’s a driven individual who also participates in both the Intercollegiate Finance Journal and TAMID Group. Outside of school, he enjoys playing tennis, skiing, and spending time with friends and family.",
  },
  {
    id: 14,
    fullName: "Ian Liu",
    title: "Senior Associate",
    imageName: "ian-pic.jpeg",
    bio: "Ian is a junior from Oradell, NJ concentrating in Applied Mathematics-Computer Science with a focus in AI/ML. Interested in the intersections between finance and technology, Ian is also an analyst for the Brown Investment Group and hopes to work at a fintech company in the summer. Outside of the classroom, Ian is a member of the Brown Men's Rugby Team, and enjoys spending time with friends and trying new foods.",
  },
  {
    id: 15,
    fullName: "Gidget Rosen",
    title: "Senior Associate",
    imageName: "gidget-pic.jpeg",
    bio: "Gidget is a junior from New York, NY pursuing a double concentration in International and Public Affairs with a focus in international security and Economics. She currently works on the business teams of the Brown Political Review and the Intercollegiate Finance Journal. In her free time, she enjoys learning languages, skiing, cooking, traveling, and playing viola.",
  },
  {
    id: 16,
    fullName: "Zandy Swartzman",
    title: "Senior Associate",
    imageName: "zandy-pic.jpeg",
    bio: "Zandy is a junior from Kansas City, MO, pursuing a double concentration in History and Economics. With a deep-set interest in business, particularly investing and consulting, Zandy has experience working with tech startups and electricity trading. Zandy is also involved with TAMID Group in addition to BTCG. In his free time, he loves traveling, playing guitar, and playing golf or soccer.",
  },
  {
    id: 17,
    fullName: "Anna Steffen",
    title: "Junior Associate",
    imageName: "anna-pic.jpeg",
    bio: "Anna is a sophomore from Madison, CT. She is currently working towards completing her Bachelor’s of Science in Biochemistry and Molecular Biology. She is interested in eventually pursuing a career in medicine. She previously worked at BioHaven Pharmaceuticals as an intern on the clinical operations team. In her free time, Anna likes to run, travel, and ski.",
  },
  {
    id: 18,
    fullName: "Maximilian Koehler",
    title: "Junior Associate",
    imageName: "max-pic.jpg",
    bio: "Max is a freshman from Acton, MA, pursuing a double concentration in German Studies and Applied Mathematics-Economics with a focus on finance. Outside of the classroom, he is an active member of Brown’s Investment Group and German Club, as well as being a player on Brown’s developmental ultimate team, PFunk. In his free time, Max enjoys watching soccer and football with friends, trying new foods, and traveling.",
  },
  {
    id: 19,
    fullName: "Bryce Saddler",
    title: "Junior Associate",
    imageName: "bryce-pic.png",
    bio: "Bryce is a current sophomore here at Brown concentrating in computer science and economics. Within school, he is a proud member of the Mosaic Plus club as well as the National Society of Black Engineers. He's very interested in the intersection of business and technology, and he hopes to one day become a product manager. His hobbies include watching Netflix series, playing basketball with friends, talking long walks, and enjoying deep and meaningful conversations.",
  },
  {
    id: 20,
    fullName: "Naomi Park",
    title: "Junior Associate",
    imageName: "naomi-pic.jpg",
    bio: "Naomi is a junior studying Applied Math - CS and physics. She hopes to apply her skills from a research project and a full stack internship towards her interests in the aerospace industry in addition to the realm of technology consulting. Outside of academics, Naomi enjoys cooking, running, and being outside.",
  },
  {
    id: 21,
    fullName: "James Phelan",
    title: "Junior Associate",
    imageName: "jimmy-pic.jpg",
    bio: "Jimmy is a freshman from Marin County, CA, pursuing a concentration in Applied Mathematics Computer Science specifically interested in Security and Data Science. Jimmy is currently a cadet in Army ROTC. After graduating, Jimmy hopes to apply his knowledge to a role in the intersection between defense and technology. Jimmy is also a member of the Brown University Men’s Rugby team. In his free time, Jimmy enjoys surfing, eating, playing sports, and chess.",
  },
  {
    id: 22,
    fullName: "Allen Wang",
    title: "Junior Associate",
    imageName: "allen-pic.jpg",
    bio: "Allen is a first year studying applied math--computer science. He's interested in both artificial intelligence and entrepreneurship; specifically, Allen is looking into using machine learning to help disrupt the educational field through personalized learning styles. In his free time, he enjoys playing basketball, hiking, and reading.",
  },
  {
    id: 23,
    fullName: "Abhi Tripathi",
    title: "Junior Associate",
    imageName: "abhi-pic.jpg",
    bio: "Abhi is a current sophomore from Massachusetts concentrating in Applied Math - Economics. He has a deep interest in entrepreneurship and recently served as a business development intern. He researches for the Brown Investment Group and is working on a venture. Abhi loves to play soccer and volleyball in his free time.",
  },
  {
    id: 24,
    fullName: "Henry Egan",
    title: "Junior Associate",
    imageName: "henry-pic.jpg",
    bio: "Henry Egan is a sophomore from Omaha, Nebraska, pursuing concentrations in Political Science and Economics. In addition to working with BTCG, Henry writes articles for the Intercollegiate Finance Journal and is a teaching assistant for entrepreneurship classes. He is also a member of Brown’s competitive ultimate frisbee team, Brownian Motion. In his free time, Henry enjoys spending time with his friends and family outdoors.",
  },

  {
    id: 25,
    fullName: "Kylash Ganesh",
    title: "Junior Associate",
    imageName: "kylash-pic.png",
    bio: "Kylash is a freshman from Easton, MA, pursuing a dual concentration in Business Economics and Computer Science. Interested in the intersection between finance and technology, Kylash is an Analyst for the Brown Healthcare Investment Group and has attended several hackathons. He also manages a 5-figure budget as Treasurer for the Intercollegiate Finance Journal. Outside of the classroom, Kylash enjoys eating ramen, playing basketball with friends, and cooking new foods.",
  },
  {
    id: 26,
    fullName: "Preetish Juneja",
    title: "Junior Associate",
    imageName: "preetish-pic.jpg",
    bio: "Preetish is a freshman from Singapore intending to concentrate in computer science and applied mathematics-economics on the mathematical finance track. He’s intrigued by modern artificial intelligence systems and hopes to harness their power to innovate technological solutions. Outside of school, he is a history buff, linguaphile and karaoke enthusiast.",
  },
  {
    id: 27,
    fullName: "Mindy Kim",
    title: "Junior Associate",
    imageName: "mindy-pic.png",
    bio: "Mindy is a freshman from Folsom, CA, pursuing a double concentration in Computer Science and Computational Neuroscience with a focus on AI/ML and Systems. She is currently also working for the Sponsorship Team for Hack@Brown and as a developer in Full Stack @ Brown for Sole Magazine. In her free time, she enjoys going on runs and reading on the main green.",
  },
];

export default membersList;
